import { createClient } from "@/lib/supabase/server"
import { notFound } from "next/navigation"
import { OnboardingWizard } from "@/components/onboarding/onboarding-wizard"

interface OnboardingPageProps {
  params: {
    token: string
  }
}

// ⚓ ANCHOR: PUBLIC ONBOARDING PAGE
// REASON: Mentee fills comprehensive profile via unique token link (generated by mentor)
// PATTERN: Server-side token validation → Client-side wizard component
// UX: Public route (no auth required), 6-step wizard, auto-save progress
export default async function OnboardingPage({ params }: OnboardingPageProps) {
  const supabase = await createClient()

  // Validate token and fetch mentee data
  const { data: mentee, error } = await supabase
    .from("mentees")
    .select("id, full_name, email, whatsapp, onboarding_completed, onboarding_link_expires_at")
    .eq("onboarding_token", params.token)
    .single()

  // Token not found or invalid
  if (error || !mentee) {
    notFound()
  }

  // Check if link expired
  const expiresAt = new Date(mentee.onboarding_link_expires_at)
  const isExpired = expiresAt < new Date()

  if (isExpired) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background">
        <div className="max-w-md space-y-4 rounded-lg border border-destructive bg-destructive/10 p-6 text-center">
          <h1 className="text-2xl font-bold text-destructive">Link Expired</h1>
          <p className="text-muted-foreground">
            This onboarding link has expired. Please contact your mentor to generate a new link.
          </p>
        </div>
      </div>
    )
  }

  // Check if already completed
  if (mentee.onboarding_completed) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background">
        <div className="max-w-md space-y-4 rounded-lg border bg-card p-6 text-center">
          <h1 className="text-2xl font-bold">Onboarding Already Completed</h1>
          <p className="text-muted-foreground">
            You have already completed your onboarding. Your mentor has access to your profile in the dashboard.
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background">
      <OnboardingWizard menteeId={mentee.id} menteeName={mentee.full_name} menteeEmail={mentee.email} />
    </div>
  )
}
